name: ChatBukkit
main: com.dinnerbone.bukkit.chat.ChatBukkit
version: 0.0.1
website: http://www.bukkit.org
author: The Bukkit Team
description: >
             Basic chat functionality.
             This plugin is one of the default plugins shipped with Bukkit.
commands:
  who:
    aliases: [whois, whos, player, players, listplayers]
    description: Looks up a player, returning various details about them. If no player is specified, it lists all available players.
    usage: |
           /<command> [player]
           Example: /<command> Walrus