name: ChatBukkit
main: com.dinnerbone.bukkit.chat.ChatBukkit
version: 0.0.1
website: http://www.bukkit.org
author: The Bukkit Team
description: >
             Basic chat functionality.
             This plugin is one of the default plugins shipped with Bukkit.
commands:
  whois:
    aliases: [who, whos]
    description: Looks up a player, returning various details about them
    usage: |
           /<command> [player]
           Example: /<command> Walrus