name: ChatBukkit
main: com.dinnerbone.bukkit.chat.ChatBukkit
version: 0.0.1
website: http://www.bukkit.org
author: The Bukkit Team
description: >
             Basic chat functionality.
             This plugin is one of the default plugins shipped with Bukkit.
commands:
  clear:
    description: Sends the target player a message
    usage: |
           /<command> <player> <message>
           Example: /<command> Walrus I found your bukkit!