name: ${name}
main: com.dinnerbone.bukkit.chat.ChatBukkit
version: ${version}
website: http://www.bukkit.org
author: The Bukkit Team
description: >
             Basic chat functionality.
             This plugin is one of the default plugins shipped with Bukkit.
commands:
  who:
    aliases: [whois, whos, player, players, listplayers]
    description: Looks up a player, returning various details about them. If no player is specified, it lists all available players.
    usage: |
           /<command> [player]
           Example: /<command> Walrus
  msg:
    aliases: [priv, tell]
    description: Sends a player a message
    usage: |
           /<command> <player|console> <message>
           Example: /<command> Dinosaur You're extinct! :(
  reply:
    aliases: [r]
    description: Replies to the last received message
    usage: |
           /<command> <message>
           Example: /<command> Oh no!
permissions:
  chatbukkit.msg:
    description: Allows the player to send messages to other players
    default: true
  chatbukkit.who.list:
    description: Allows the player to view who's online
  chatbukkit.who.whois:
    description: Allows the player to lookup another player's information
  chatbukkit.who:
    description: Allows the player to view who's online and their details
    default: true
    children:
      chatbukkit.who.list: true
      chatbukkit.who.whois: true
  chatbukkit.*:
    description: Gives all abilities in Chatbukkit
    children:
      chatbukkit.who: true
      chatbukkit.msg: true